name: deploy action

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: install yarn
        run: npm install -g yarn@4.0.1

      - name: install dependencies
        run: yarn install

      - name: create env
        run: echo ${{ secrets.ENV }} > .env

      - name: build
        run: npm run build

      - name: compress
        run: tar -czvf build.tar.gz build

      - name: upload to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build.tar.gz
          remote-dir: /
          exclude: .gitignore

      - name: connect to ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            tar -xzvf build.tar.gz
            rm -rf build.tar.gz
            cp -r build/* /httpdocs
            exit